# Use perl to run tests
language: perl
perl:
  - "5.16"

# Set cpanm running opts, switch nginx binary to openresty
env:
  - >
    PACKAGE_PATH="http://packages.squiz.co.uk/ubuntu/12.04"
    OPENRESTY_PACKAGE="openresty_1.4.3.3-1_amd64.deb"
    RESTY_HTTP_REPO="https://github.com/pintsized/lua-resty-http.git"
    RESTY_HTTP_PATH="../lua-resty-http"
    
    OPENRESTY_LOG_PATH="/var/log/openresty"
    PERL_CPANM_OPT="--notest --force --skip-satisfied" 
    TEST_NGINX_BINARY="openresty" 
    PATH="$PATH:/opt/openresty/sbin"

# Install openresty package from squiz repo
before_install:
  # Install openresty
  - "wget $PACKAGE_PATH/$OPENRESTY_PACKAGE && sudo dpkg --force-depends -i $OPENRESTY_PACKAGE"
  - "sudo apt-get -f install" # Fix dependencies of the installed package if required.
  - "sudo chmod -R 777 $OPENRESTY_LOG_PATH" # Make sure the default log can be written to by an unprivileged user

  # Grab lua-resty-http
  - "git clone $RESTY_HTTP_REPO $RESTY_HTTP_PATH"

# Install Test::Nginx suite via cpanm
install:
  - "cpanm Test::Nginx" 

#before_script: "sudo stop redis-server" # Make sure the default redis is stopped
script: "make test_all"
